export const enterprisePageConfigs = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Real-time monitoring of risk operations and system status",
    mode: "dashboard",
    endpoint: "/api/platform/dashboard",
    allowCreate: false,
  },
  events: {
    title: "Risk Events",
    subtitle: "Search and triage assessment events with fast filters and workflows",
    endpoint: "/api/modules/events",
    columns: ["id", "customerRef", "deviceUuid", "ipAddress", "riskScore", "riskLevel", "status", "createdAt"],
    allowCreate: true,
    actionButtons: ["investigate", "escalate", "resolve"],
  },
  devices: {
    title: "Devices",
    subtitle: "Device profiles, risk posture, and identity linkage insights",
    endpoint: "/api/modules/devices",
    columns: ["deviceUuid", "riskScore", "riskLevel", "associatedCustomers", "rooted", "emulator", "lastSeen"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  customers: {
    title: "Customers",
    subtitle: "Customer risk profiles with history, device footprint, and status",
    endpoint: "/api/modules/customers",
    columns: ["customerHash", "riskScore", "riskLevel", "deviceCount", "assessmentHistory", "status"],
    allowCreate: true,
    actionButtons: ["acknowledge"],
  },
  alerts: {
    title: "Alerts",
    subtitle: "Risk, compliance, and security alert lifecycle management",
    endpoint: "/api/modules/alerts",
    columns: ["category", "title", "severity", "workflow", "owner", "status", "createdAt"],
    allowCreate: true,
    actionButtons: ["acknowledge", "investigate", "escalate", "resolve"],
    tabs: ["All", "Risk", "Compliance", "Security"],
  },
  analytics: {
    title: "Analytics",
    subtitle: "Assessment volume, trend intelligence, and network breakdowns",
    mode: "dashboard",
    endpoint: "/api/analytics/overview",
    allowCreate: false,
  },
  fraudHeatMap: {
    title: "Fraud Heat Map",
    subtitle: "Manage location risk entries and run manual aggregation",
    endpoint: "/api/modules/fraud-heat-map",
    columns: ["location", "country", "riskScore", "events"],
    allowCreate: true,
    actionButtons: ["manual-aggregate"],
  },
  reports: {
    title: "Reports",
    subtitle: "Generate on-demand reports and manage recurring report schedules",
    endpoint: "/api/modules/reports",
    columns: ["name", "type", "format", "status", "cron"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  challengeAnalytics: {
    title: "Challenge Analytics",
    subtitle: "Challenge success/failure trends, provider performance, and outcomes",
    endpoint: "/api/modules/challenge-analytics",
    columns: ["method", "volume", "successRate", "provider"],
    allowCreate: false,
    actionButtons: ["export"],
  },
  outcomeLearning: {
    title: "Outcome Learning",
    subtitle: "Outcome feedback loops for tuning rules from production behavior",
    endpoint: "/api/modules/outcome-learning",
    columns: ["rule", "likelyFraud", "likelyLegit", "unknown", "lastSync"],
    allowCreate: false,
  },
  experiments: {
    title: "Experiments",
    subtitle: "A/B experimentation for scoring rules and engine configuration",
    endpoint: "/api/modules/experiments",
    columns: ["name", "status", "variants", "tenantScope", "startDate"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  uiExperiments: {
    title: "UI Experiments",
    subtitle: "Dashboard UX experiments and interaction lift tracking",
    endpoint: "/api/modules/ui-experiments",
    columns: ["name", "targetArea", "status", "interactionDelta"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  platformSettings: {
    title: "Platform Settings",
    subtitle: "Global defaults, hard-fail controls, and risk weight governance",
    endpoint: "/api/modules/platform-settings",
    columns: ["setting", "enabled", "threshold", "weight"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  categoryScoring: {
    title: "Category-based Scoring",
    subtitle: "Versioned category weight management with rollback-ready controls",
    endpoint: "/api/modules/category-scoring",
    columns: ["context", "version", "status", "updatedBy"],
    allowCreate: true,
  },
  metricWeights: {
    title: "Metric Weights",
    subtitle: "Fine-tune onboarding and lifecycle metric influence values",
    endpoint: "/api/config/weights",
    mode: "weights",
    allowCreate: false,
  },
  v2Scoring: {
    title: "Rule-based Scoring",
    subtitle: "Signal weight and stacking logic configuration with overrides",
    endpoint: "/api/modules/v2-scoring",
    columns: ["ruleName", "signalWeight", "tenant", "touchpoint", "enabled"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  scoringMetrics: {
    title: "Scoring Metrics",
    subtitle: "Operational metrics of scoring config loads and performance",
    endpoint: "/api/admin/model-info",
    mode: "scoring-metrics",
    allowCreate: false,
  },
  behavioral: {
    title: "Behavioral Learning",
    subtitle: "Behavioral intelligence controls and anomaly sensitivity tuning",
    endpoint: "/api/modules/outcome-learning",
    columns: ["rule", "likelyFraud", "likelyLegit", "unknown", "lastSync"],
    allowCreate: false,
  },
  challengeRules: {
    title: "Challenge Rules",
    subtitle: "Step-up challenge rule engine with tenant-specific controls",
    endpoint: "/api/modules/challenge-rules",
    columns: ["tenant", "method", "condition", "enabled"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  challengeProviders: {
    title: "Challenge Providers",
    subtitle: "External challenge provider lifecycle and health management",
    endpoint: "/api/modules/challenge-providers",
    columns: ["provider", "type", "health", "enabled"],
    allowCreate: true,
    actionButtons: ["toggle", "test-connectivity"],
  },
  secretQuestions: {
    title: "Secret Questions",
    subtitle: "Knowledge-based challenge question pool and tenant settings",
    endpoint: "/api/modules/secret-questions",
    columns: ["question", "active", "tenant"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  intelligence: {
    title: "Intelligence",
    subtitle: "Threat repository and external feed orchestration",
    endpoint: "/api/modules/intelligence",
    columns: ["repository", "entries", "syncSchedule", "status"],
    allowCreate: true,
    actionButtons: ["test-connectivity"],
  },
  fraudTools: {
    title: "Fraud Tools",
    subtitle: "Known fraud-tool signature management and severity governance",
    endpoint: "/api/modules/fraud-tools",
    columns: ["toolName", "category", "severity", "active"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  emulatorSignatures: {
    title: "Emulator Signatures",
    subtitle: "Emulator detection signatures with confidence and source tracking",
    endpoint: "/api/modules/emulator-signatures",
    columns: ["signatureType", "value", "confidence", "source", "active"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  tenantRetention: {
    title: "Tenant Retention",
    subtitle: "Tenant-scoped retention controls for risk and compliance datasets",
    endpoint: "/api/modules/tenant-retention-policies",
    columns: ["tenant", "dataType", "retentionDays", "archiveEnabled"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  apiKeys: {
    title: "API Keys",
    subtitle: "Tenant API key lifecycle and integration scope management",
    endpoint: "/api/modules/api-keys",
    columns: ["tenant", "touchpoint", "keyName", "status", "lastUsed"],
    allowCreate: true,
    actionButtons: ["toggle", "revoke"],
  },
  providers: {
    title: "Providers",
    subtitle: "External service provider health, credentials, and alerts",
    endpoint: "/api/modules/providers",
    columns: ["provider", "serviceType", "health", "enabled"],
    allowCreate: true,
    actionButtons: ["toggle", "test-connectivity"],
  },
  users: {
    title: "Users",
    subtitle: "Admin user lifecycle with tenant and role controls",
    endpoint: "/api/modules/users",
    columns: ["name", "email", "tenant", "role", "status"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  tenants: {
    title: "Tenants",
    subtitle: "Tenant lifecycle and usage posture management",
    endpoint: "/api/modules/tenants",
    columns: ["name", "status", "plan", "users", "touchpoints"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  audit: {
    title: "Audit Logs",
    subtitle: "Search and export privileged action trails with retention visibility",
    endpoint: "/api/modules/audit-logs",
    columns: ["action", "user", "resource", "tenant", "timestamp"],
    allowCreate: false,
  },
  hubSpoke: {
    title: "Hub-Spoke",
    subtitle: "Hub-spoke synchronization observability and controls",
    endpoint: "/api/modules/hub-spoke",
    columns: ["spoke", "status", "lastSync", "lagSeconds"],
    allowCreate: true,
    actionButtons: ["manual-sync"],
  },
  hubSharing: {
    title: "Hub Sharing",
    subtitle: "Resource sharing policy management from hub to spokes",
    endpoint: "/api/modules/hub-sharing",
    columns: ["resourceType", "shareEnabled", "scope"],
    allowCreate: true,
    actionButtons: ["toggle"],
  },
  compliance: {
    title: "Compliance",
    subtitle: "Privacy workflows, DSR operations, and policy controls",
    endpoint: "/api/modules/compliance",
    columns: ["requestType", "subjectRef", "status", "priority", "dueDate"],
    allowCreate: true,
    actionButtons: ["process-dsr", "complete-dsr"],
  },
  health: {
    title: "Health",
    subtitle: "Service health and platform performance telemetry",
    endpoint: "/api/modules/health",
    columns: ["service", "status", "latencyMs", "cpu", "memory"],
    allowCreate: false,
  },
  importData: {
    title: "Import",
    subtitle: "Multi-step import operations and schedule visibility",
    endpoint: "/api/modules/import",
    columns: ["importType", "filename", "status", "rows", "runAt"],
    allowCreate: true,
    actionButtons: ["run-import"],
  },
};
